version: '3.8'
services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "18080:8080"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    command: ["java", "-jar", "-Dspring.profiles.active=test", "app.jar"] 