input {
  file {
    path => ["/var/log/app/*.log"]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/plugins/inputs/file/.sincedb-korean-fortune"
    codec => plain {
      charset => "UTF-8"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "korean-fortune-%{+YYYY.MM.dd}"
  }
}
