CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    username VARCHAR(100) UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255),
    profile_image_url VARCHAR(500),
    birth_year INTEGER,
    birth_month INTEGER,
    birth_day INTEGER,
    birth_hour INTEGER,
    birth_minute INTEGER,
    gender VARCHAR(10),
    calendar_type VARCHAR(10),
    birth_location VARCHAR(100),
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    provider_id VARCHAR(100),
    enabled BOOLEAN DEFAULT TRUE,
    account_locked BOOLEAN DEFAULT FALSE,
    email_verified BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMP,
    last_login_at TIMESTAMP,
    login_count INTEGER DEFAULT 0,
    failed_login_attempts INTEGER DEFAULT 0,
    password_changed_at TIMESTAMP,
    preferred_language VARCHAR(10) DEFAULT 'KOREAN',
    timezone VARCHAR(50) DEFAULT 'Asia/Seoul',
    ai_features_enabled BOOLEAN DEFAULT TRUE,
    notification_enabled BOOLEAN DEFAULT TRUE,
    marketing_emails_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_provider ON users (auth_provider, provider_id);
CREATE INDEX idx_users_created_at ON users (created_at);
CREATE INDEX idx_users_birth_date ON users (birth_year, birth_month, birth_day);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE saju_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    year_pillar VARCHAR(2) NOT NULL,
    month_pillar VARCHAR(2) NOT NULL,
    day_pillar VARCHAR(2) NOT NULL,
    time_pillar VARCHAR(2),
    day_master VARCHAR(1) NOT NULL,
    calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_id ON saju_data (user_id);
CREATE INDEX idx_calculated_at ON saju_data (calculated_at);

CREATE TABLE security_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent TEXT,
    success BOOLEAN NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSON
);

CREATE INDEX idx_audit_user ON security_audit_log (user_id);
CREATE INDEX idx_audit_timestamp ON security_audit_log (timestamp);
CREATE INDEX idx_audit_action ON security_audit_log (action);

CREATE TABLE tojeong_gwa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gwa_number INTEGER NOT NULL UNIQUE,
    gwa_name VARCHAR(10) NOT NULL,
    gwa_symbol VARCHAR(5) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    detailed_fortune TEXT NOT NULL,
    overall_score INTEGER NOT NULL DEFAULT 50
);

-- Supabase의 public schema는 Data API에 노출될 수 있으므로 기본 차단한다.
-- DB-only 범위에서는 anon/authenticated 정책을 만들지 않는다.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE saju_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE tojeong_gwa ENABLE ROW LEVEL SECURITY;
