CREATE TABLE notification_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_key VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL,
    recipient_name VARCHAR(50) NOT NULL,
    email VARCHAR(254),
    telegram_chat_id VARCHAR(32),
    discord_webhook_target VARCHAR(40),
    notification_type VARCHAR(16) NOT NULL,
    birth_year INTEGER NOT NULL,
    birth_month INTEGER NOT NULL,
    birth_day INTEGER NOT NULL,
    birth_hour INTEGER NOT NULL,
    birth_minute INTEGER NOT NULL,
    gender VARCHAR(1) NOT NULL,
    calendar_type VARCHAR(8) NOT NULL,
    leap_month BOOLEAN NOT NULL,
    birth_longitude DOUBLE PRECISION,
    apply_equation_of_time BOOLEAN NOT NULL,
    apply_historical_dst BOOLEAN NOT NULL,
    scheduled_time TIME NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    last_run_date DATE,
    last_status VARCHAR(16),
    last_error VARCHAR(500),
    last_run_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_notification_schedule_owner
    ON notification_schedule (owner_key);
CREATE INDEX idx_notification_schedule_due
    ON notification_schedule (enabled, last_run_date, scheduled_time);

ALTER TABLE notification_schedule ENABLE ROW LEVEL SECURITY;
